import NavBar from "@/components/navBar";
import Image from "next/image";

export const metadata = {
  title: "Home Page - Hello its home-page of next js",
  description: "Generated by create next app",
};

export default function Home() {
  return (
   <>
   < NavBar />
   I am home
   <div className="container">
   <Image className="mx-auto"
      src="https://images.pexels.com/photos/24405951/pexels-photo-24405951/free-photo-of-the-aurora-bore-is-seen-in-the-sky-over-a-forest.jpeg?auto=compress&cs=tinysrgb&w=400&lazy=load"
      alt="Picture of the author"
      width={300}
      height={500}
    />
   </div>
   </>
  );
}
