import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Admin - Al MFB  ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
          <div>Header of admin <br />
             {children} <br />
             Footer of admin
          </div>
  );
}
